---
##############################################################################
# mit-venv v2024-10-29
##############################################################################

- name: Copy requirements.txt
  ansible.builtin.copy:
    src: requirements.txt
    dest: /opt/mit-zabbix-maintenance/

- name: Install python3-venv
  ansible.builtin.apt:
    pkg: python3-venv

- name: Install pip in venv
  ansible.builtin.pip:
    name: pip
    virtualenv: /opt/mit-zabbix-maintenance/.venv
    virtualenv_command: python3 -m venv

- name: Updated python dependencies (requirements.txt)
  ansible.builtin.pip:
    virtualenv_command: python3 -m venv
    requirements: /opt/mit-zabbix-maintenance/requirements.txt
    virtualenv: /opt/mit-zabbix-maintenance/.venv
  environment: "{{ proxy_env }}"

- name: Copy zabbix-maintenance.py
  ansible.builtin.copy:
    src: zabbix-maintenance.py
    dest: /opt/mit-zabbix-maintenance/bin/
    mode: "0755"

- name: Remove deprecated files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /usr/local/lib/python2.7/dist-packages/zabbix_api.py
    - /usr/local/lib/python3.7/dist-packages/zabbix_api.py
    - /usr/local/lib/python3.9/dist-packages/zabbix_api.py
    - /usr/lib/zabbix/externalscripts/zabbix-maintenance.py
