---

- name: Copy zabbix-maintenance.py
  copy:
    src: zabbix-maintenance.py
    dest: /usr/lib/zabbix/externalscripts/
    mode: 0755

- name: Install python3-pip
  apt: 
    pkg: python3-pip

# https://github.com/gescheit/scripts
- name: Install zabbix-api via pip3
  pip:
    executable: pip3
    name: zabbix-api

# WIP, v0.4 -> https://github.com/gescheit/scripts/blob/master/zabbix/zabbix_api.py from 2021-05-31
# Adds validate_certs
- name: Copy zabbix_api.py
  copy:
    src: zabbix_api.py
    dest: /usr/local/lib/python3.7/dist-packages/
  when: "ansible_hostname == 'zabbix'"

